# Generated by Django 5.2.17 on 2026-09-11 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default='room-01', max_length=32)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=40)),
                ('room_id', models.CharField(max_length=32)),
                ('event_time', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.player')),
            ],
            options={
                'indexes': [models.Index(fields=['published_at', 'event_time'], name='game_gameev_publish_3ab2a5_idx')],
            },
        ),
    ]
